up

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -175,7 +175,13 @@ jobs:
             fi
           done
 
-          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
+          echo "$MATRIX" | jq . > /dev/null 2>&1
+          if [ $? -eq 0 ]; then
+            echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
+          else
+            echo "Error: Invalid JSON format in MATRIX"
+            exit 1
+          fi
 
   building:
     needs: set-env
